# R 4.4.2
suppressWarnings(suppressMessages(library(cowplot))) # 1.1.3
suppressWarnings(suppressMessages(library(dplyr))) # 1.1.4
suppressWarnings(suppressMessages(library(echarts4r))) # 0.4.5
suppressWarnings(suppressMessages(library(ggimage))) # 0.3.3
suppressWarnings(suppressMessages(library(ggplot2))) # 3.5.1 
suppressWarnings(suppressMessages(library(gridExtra))) # 2.3
library(here) # 1.0.1
suppressWarnings(suppressMessages(library(httr))) # 1.4.7
library(knitr) # 1.49
suppressWarnings(suppressMessages(library(lubridate))) # 1.9.3
suppressWarnings(suppressMessages(library(magick))) # 2.8.5
suppressWarnings(suppressMessages(library(plotly))) # 4.10.4
suppressWarnings(suppressMessages(library(RMySQL))) # 0.10.29
library(rlang) # 1.1.4
library(scales) # 1.3.0
suppressWarnings(suppressMessages(library(sf))) # 1.0-19
library(stringr) # 1.5.1
library(tibble) # 3.2.1
library(tidyr) # 1.3.1