name: Run R Script (Docker)

on:
  workflow_dispatch:      
  schedule:                
    - cron: '0 0 1 * *'     

jobs:
  run-rscript:
    runs-on: ubuntu-latest

    # Chargement de l'image docker
    container:
      image: mpretet/image_fiche_opj:4.1.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Exécution du script
      - name: Run R Script
        run: Rscript programs/boucle_quarto.R

      # Sauvegarde des résultats
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: docs/
          retention-days: 30